### ISSUE TITLE
How to run on Apple Silicon MacBook Pro? 

### ISSUE THREAD

**Issue by zinwalin** [vkoskiv/c-ray#106]
The instructions for Mac is not working on MacBook Pro M1.  Need your help.

**Comment by vkoskiv** [comment]
Hey! Thanks for checking out c-ray. Could you post a screenshot or a snippet of what kind of error you encountered? I've tested it briefly on M1, but it's possible I haven't ironed out possible build issues yet.

**Comment by vkoskiv** [comment]
If you're using Xcode, then I think 75231eb25c5808cd34182a505202d04337061dfd will resolve your issue. Pull and try again.

You could also try out the linux/cmake instructions if you don't mind installing cmake, I keep it up to date since I personally use that one for building.

**Comment by zinwalin** [comment]
> 

![image](https://user-images.githubusercontent.com/5416196/147397726-260a1747-570b-4bc8-a219-21f508c82ca6.png)

**Comment by vkoskiv** [comment]
There it is, forgot those were even in there still. I think they are some kind of x86-specific flags.
I just [removed](https://github.com/vkoskiv/c-ray/commit/c8b69090c3f7eebac181159a02519ee550e16b4f) them - If you could pull again and report back if it worked, that'd be great.

**Comment by zinwalin** [comment]
> 

Hi vkoskiv, thanks for your quick reply, it works now.   BTW, how did you start CMakeLists.txt from scratch?

**Comment by vkoskiv** [comment]
Yeah, the CMakeLists file was written from scratch a few years ago. I didn't bother learning it fully, so it's quite possible it could be restructured to be more optimal. But it works fine for my usage, so I haven't touched it.

**Comment by vkoskiv** [comment]
Seems resolved, let me know if you have further questions.
