### ISSUE TITLE
Terrible performance on Linux

### ISSUE THREAD

**Issue by VKoskiv** [VKoskiv/c-ray#42]
Abnormally low performance under more recent Linux kernels. Seems to spend vast amounts of time in kernel space for some reason.
Unable to debug further at this point.

**Comment by VKoskiv** [comment]
Resolved in 801c621c7c4ff6a9f8eb1cb7fdc33504a9a6a8b6

Turns out, glibc rand() has locks in it, not good for a multi-threaded app.

**Comment by cmsimike** [comment]
woo
