### ISSUE TITLE
Flatten k-d trees.

### ISSUE THREAD

**Issue by VKoskiv** [VKoskiv/c-ray#68]
I read that it's good practice to flatten the binary tree into a flat array structure using a good heuristic. Should look into implementing this. Apparently there is a performance gain!

**Comment by madmann91** [comment]
The new BVH implementation is already a flat array of nodes, so unless you want to also rework the old implementation, I think this issue can be closed.

**Comment by VKoskiv** [comment]
Yep, effectively resolved by 9010e295e620027d885ebb585abe309816e7c450
